project_name: lw-runs
learning_rate: 0.001
batch_size: 64
delta: 0.00001 # needs tuning
patience: 5 # needs tuning
max_epochs: 10
patch_size: 128
validation_size: 10000
device: cuda
image_dtype: float32
params_dtype: float64
log_interval: 50
val_interval: 600
split_seed: 42
